# Generated by Django 5.1.7 on 2025-05-07 06:02

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('video', models.FileField(blank=True, null=True, upload_to='lesson_videos/')),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Darsning nazariy qismi',
                'verbose_name_plural': 'Darsning nazariy qismlari',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
            options={
                'verbose_name': 'Yil',
                'verbose_name_plural': 'Yillar',
            },
        ),
        migrations.CreateModel(
            name='AcademicPartFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('academic_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='subject.academicpart')),
            ],
            options={
                'verbose_name': 'Fayl',
                'verbose_name_plural': 'Fayllar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='subject.academicpart')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='subject.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izohlar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, verbose_name="Qisqacha ma'lumot")),
                ('teachers', models.ManyToManyField(related_name='lesson_teacher', to='account.teacherprofile')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
            },
        ),
        migrations.AddField(
            model_name='academicpart',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='subject.lesson'),
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_session', to='subject.lesson')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_teachers', to='account.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, verbose_name="Qisqacha ma'lumot")),
                ('image', models.ImageField(blank=True, null=True, upload_to='subject_images/')),
                ('semester', models.CharField(choices=[('SPRING', 'Bahorgi'), ('AUTUMN', 'Kuzgi')], default='AUTUMN', max_length=15)),
                ('begin_at', models.DateField(auto_now=True)),
                ('end_at', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='account.faculty')),
                ('groups', models.ManyToManyField(related_name='subjects_group', to='account.group')),
                ('teachers', models.ManyToManyField(related_name='subjects_teacher', to='account.teacherprofile')),
                ('year', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='subject.year')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_subject', to='subject.subject'),
        ),
        migrations.CreateModel(
            name='AcademicPartReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('academic_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='subject.academicpart', verbose_name='Nazariy qism')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reaksiya',
                'verbose_name_plural': 'Reaksiyalar',
                'unique_together': {('academic_part', 'user')},
            },
        ),
    ]
